[build]
  publish = "your-public-folder" # E.g., "dist", "public", etc.
  command = "npm run build" # If applicable; otherwise, leave empty

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
